name = "matterfi"

[contracts.master_payment_code]
path = "src/master_payment_code.rs"
name = "master_payment_code"
fqn = "matterfi::MasterPaymentCode"

[backends.casper]
name = "casper"
dependency_name = "casper"

[backends.casper.dependency]
version = "*"
features = []
optional = false
